from test_transform import main as main_transform
from test_exception import main as main_exception


if __name__ == '__main__':
    main_transform()
    main_exception()
